### ISSUE TITLE
Not working on Prime LE

### ISSUE THREAD

**Issue by kfeeeeee** [krtkl/snickerdoodle-examples#2]
@krtklbush @Weatherbee 
Unfortunately, I could not get the emio-spi example to work on the snickerdoodle prime.
Here is what I tried:

-> Regenerated everything in vivado 2017.4
-> Exported hardware
-> Created fsbl project in sdk using the exported hardware
-> Generated boot.img using the created fsbl.elf, bitstream and the provided u-boot.elf.

No matter what I try the result of spitest is always:

0x00 0x00 0x00 0x00

Attached, you will find my devicetree.dts (as txt for github) and the bif file (as txt). I really hope it is my fault and not a hardware issue.

Thank you.

[devicetree.txt](https://github.com/krtkl/snickerdoodle-examples/files/1838025/devicetree.txt)
[FSBL.txt](https://github.com/krtkl/snickerdoodle-examples/files/1838032/FSBL.txt)

**Comment by russbush** [comment]
Can you show how you are invoking the command and explain a bit how/what you are connecting the SPI pins to. To test the example project, I looped the MOSI and MISO pins by jumpering them together. Your process is exactly what it should be so there seems to be some other issue at play. Are you naming your boot image “boot.img” in the SD card? Can you confirm that he bitstream is being loaded (breathing pattern on app/White LED)?

**Comment by kfeeeeee** [comment]
@krtklbush Thanks for your fast reply. I have retested everything and it turns out it was a problem with the jumpers I have used - changed the jumper and everything works now! I am glad it was not a hardware fault. :+1:
